# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Builder-SessionManager
version:      1.00
version_from: lib/CGI/Builder/SessionManager.pm
installdirs:  site
requires:
    Apache::SessionManager:        1.01
    CGI::Builder:                  1.2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
